### ISSUE TITLE
How many gpus is need to train this model?

### ISSUE THREAD

**Issue by xmu-xiaoma666** [Youwang-Kim/CLIP-Actor#1]
Thanks for your great project. I would like to know how many gpus is need to train this model?

**Comment by Youwang-Kim** [comment]
Thank you for your interest to our paper! 
For training, we train a single motion sequence for 0.5~1 hrs using a single RTX TITAN (24GB RAM).
Please refer to P23 (Sec. E of the supplementary material) for more details.
